import React, { Component } from 'react';

import Head from 'next/head';
class PrivacyPlans extends Component {
    render() {
        return (
            <div>
                <Head>
                    <link href="https://fonts.googleapis.com/css?family=Montserrat:300,400,500,600,700&display=swap" rel="stylesheet" />
                    <link href="/static/style.css" rel="stylesheet" />
                </Head>
                <main className="main about-us privacy">
                    <div className="shape-large">
                        <img src="images/icon-huge-leaf.png" alt="Image Description" />
                    </div>

                    <div className="banner">
                        <div className="container">
                            <img src="images/banner.jpg" alt="Image Description" />
                            <span className="img-shape">
                                <img src="images/icon-leaf.png" alt="image description" />
                            </span>
                        </div>
                    </div>
                    <div className="intro">
                        <span className="img-shape">
                            <img src="images/icon-leaf-small.png" alt="image description" />
                        </span>
                        <div className="block">
                            <h1>Aesthetic Record <span>Privacy Policy</span></h1>
                            <span className="title">A.  Introduction</span>
                            <p>
                                Aesthetic   Record   (“Aesthetic   Record,   “we,”,   or   “us”)  knows   that   you   value   your   privacy.Aesthetic   Record   owns   and   operates   multiple   applications,   tools,   and   services;   owns   andoperates various public-facing websites; operates several Facebook pages and/or groups alongwith  pages  or  accounts  on  other  social  media   platforms;  and   delivers   the   same   or  similarcontent available to mobile users (collectively, the “Services”).   This Privacy Policy applieswhen you utilize any of these Services and also describes how your information is collected,used,   shared,   and   secured,   as   well   as   your   related   choices   regarding   use,   access   andcorrection.Our   Privacy   Policy   does   not   apply   to   the   information   we   receive   from   the   third-partywebsites, mobile apps and other digital products that use our Services.The Privacy Policy also does not apply to websites maintained by other companies or organizations to which we may link or who may link to us.   You should consult the relevant privacy policies on thewebsites affiliated with those companies or organizations to find out more about their privacypractices and your related choices.  We are not responsible for the actions and privacy policiesof third party websites. <strong>By using our Services, you are accepting the practices described in our Privacy Policy,including our use of cookies and similar online tools. </strong>
                            </p>
                        </div>
                        <div className="block">
                            <p>We may change this Privacy Policy to   accommodate   changes   to   our  Services,   new   technologies   or   industry   practices,   updated regulatory or legal requirements, or for other purposes.   We reserve the right to modify oramend the terms of this Privacy Policy from time to time without notice. Your continued useof our Services following the posting of changes to these terms will mean you accept thosechanges.  If   we   intend   to   apply   the   modifications   or   amendments   to   this   Privacy   Policy retroactively or to personal information already in our possession, we will provide you with notice of the modifications or amendments and seek your consent for such use.  Notices maybe emailed to the most recent email address you provided us, by posting notice of such changeon   an  Aesthetic   Record   website,   or   by   other   communication   channels.     You   consent   toreceiving notices in these ways.   We reserve the right to determine the form and means ofproviding notifications to you, consistent with applicable law. <strong>If you are a resident of California, please see the Important Information for CaliforniaResidents Section of this Privacy Policy.If you are a resident of Nevada, please see the Important Information for NevadaResidents Section of this Privacy Policy.</strong> </p>
                        </div>
                        <div className="block">
                            <span className="title">B.  Information We Collect</span>
                            <p>When you use our Services, we may collect the following categories of information, which may be considered personal information when maintained in identifiable form: </p>
                            <p>1. <strong> First name and surname, year of birth, username and password, gender, email address,   contact   information,</strong>   country   of   residence,   employment,   and   otherinformation  you provide us when you create an account with us; sign-up to receivecommunications or materials from us; place an order; enter a contest; submit content orpost feedback and/or comments; send us an email or request for information; or otherwisesubmit a form to us.</p>
                            <p>2. <strong>Transaction and payment information you provide</strong>  when   purchasing   a   product   orService from us, whether via an Aesthetic Record website or elsewhere. This informationmay include the information listed above as well as payment information.</p>
                            <p>3. <strong>Usage, viewing, logs, metrics and other device and technical data</strong> collected when you visit an Aesthetic Record website, utilize our Services as an end user, or open or reply toemails we send.  Usage information could include the time, date, and duration of your useof   our   Services;   your   interaction   with   content   offered   through   the   Services,   and   any referring   websites.     Device   information   may   include   information   such   as   your   webrequest, Internet Protocol (“IP”) address, device identifiers, device information (such as type and model, operating system type, browser type, language, and settings), mobile ad identifiers, cookie IDs, referring / exit pages and URLs, interaction information (such asclickstream data), domain names, pages viewed, software crash data, and other similar technical data.   Our servers may automatically keep an activity log of your use of the Services.</p>
                            <p>4. <strong>Information collected from third party or public or commercially-available sources</strong> or that we receive from companies that partner with us to provide products and Services.This   may   include   information   we   receive   from   our   advertising   and   market   researchpartners, who may provide us with information about your interest in and engagementwith our online advertisements.   When you interact with any Aesthetic Record page oraccount on a social media platform, we may collect the personal information that youmake available to us on that page or account, including your social media account ID.We will comply with the privacy policies of the social media platform and we will onlycollect and store such personal information that we are permitted to collect by thosesocial media platforms.With your consent, we also may share information about youractivities, including what you view on our websites, with that social network’s users.</p>
                            <p>5. <strong>Location information</strong> when you visit an Aesthetic Record website or use our Services,including location information either provided by a mobile device interacting with one of our sites or applications or associated with yourIP address.  Advertisements and contentmay be directed at you based on this data.</p>
                            <p>6. <strong>Content you choose to upload to the Services</strong> such as text, images, audio, and video,along with the metadata associated with the files you upload.</p>
                        </div>
                        <div className="block">
                            <span className="title">C. How We Use Information</span>
                            <p>We use your information in the ways described below, as well as in other ways to which you consent:</p>
                            <p><strong>1. Process your orders and requests and respond to your questions and concerns;</strong> for example, if you inquire about our Services, we may use your data to respond to and process such requests.</p>
                            <p><strong>2. Provide  the Products or Services You Request</strong>  such   as   using   your   information   to process   any   subscriptions   you   pay   for;   sending   you   electronic   newsletters;   postingcontent or feedback you submit; and enabling your participation in features that are partof the Services.  We also provide personalized content and suggestions to you, including by email, based on your interest and preferences. To enable us to provide these Services,we may use the information we collect to identify you across sessions, browsers, and /or devices.</p>
                            <p><strong>3. Communicate with you about your account or transactions (by email text, or othermedium), and provide you with product or Service-related communications,</strong> such asinformation   about   policy   updates;   newsletters,   invitations   to   events;   offers   orannouncements   about   current   or   beta   products   or   Services;   offers   or   announcementsabout third party partners’ products or services; communications about your comments orfeedback; online surveys; and other important information about Aesthetic Record.</p>
                            <p><strong>4. Provide you with targeted advertising and promotions</strong> on behalf of ourselves and ourthird party advertisers, both on our websites and elsewhere. Please see the “Your PrivacyControls and Choices” and “Third Party Sites, Services, and Applications” sections ofthis Privacy Policy for further information about our and third parties’ use of cookies,web beacons, SDKs, and other tracking technologies to provide you relevant ads, as wellas information about how to disable cookies and make other choices related to targeted advertising. We may also use your information to measure and report on the delivery ofadvertisements.</p>
                            <p><strong>5. Learning about our users and Services by</strong>  researching   our   users’  demographics,interests and behavior, including performing statistical analysis of our users, their use ofthe   Services,  and   their   purchasing   patterns.  We   do  this   to   optimize   and   improve   theServices, our products, and our operations.</p>
                            <p><strong>6. Detect, investigate and prevent activities that may violate our policies or applicable laws;</strong> or that may threaten the security, integrity or availability of our or another party’sproducts, systems and Services; or to protect, enforce, or defend the legal rights, privacy,safety, or property of Aesthetic Record, its agents, officers, directors, and employees.</p>
                            <p>We may use the information from one aspect of the Services for other aspects of Services andwe may combine information gathered from multiple aspects of the Services into a single user record. We also may use or combine information that we collect offline or we collect or receive from third-party sources for many reasons, including to enhance, expand, and checkthe accuracy of our records. Additionally, data collected from a particular computer, browseror   device   may   be   used   with   another   computer,   browser   or   device   that   is   linked   to   the computer, browser or device on which such data was collected.</p>
                            <p>We also use anonymous information, such as usage data and aggregated data, for other lawfulpurposes, such as to create blog posts and content that others may find useful.</p>
                        </div>
                        <div className="block">
                            <span className="title">D.  Information We Collect</span>
                            <p>As described below, our information sharing practices vary based on the type information and the recipient:</p>
                            <p><strong>1. Third Party Service Providers.</strong> Third party agents and vendors perform functions on our   behalf,   including,   but   not   limited   to,   hosting,   content   syndication,   contentmanagement tools, applications, social media integration, marketing, analytics, billing,shipping, and customer service.  These entities may have access to personal informationif needed to perform their functions.  If such access is required, the third parties will beobligated to maintain the confidentiality and security of that personal information.  Theyare restricted from using, selling, distributing or altering this data in any way other thanto provide the requested services to Aesthetic Record.</p>
                            <p><strong>2. Third Party Business Partners.</strong> From time to time, we allow companies whose productsor services we feel may interest our readers to advertise to them, using the names andemail addresses provided to us by our users. We do not share this information directlywith these companies, however, we may send relevant communications on behalf of thesecompanies because many of our users find this to be a valuable and time-saving service. If you do not want your information used for these purposes, you can opt-out of such useby e-mailing us at privacy@Aesthetic Record.com, or calling or writing us at the contactinformation provided below in the “Contact Us” section.</p>
                            <p><strong>3. Third Party Content or Advertising Partners.</strong> When you use our Services, third partiesthat provide content, advertising, or functionality to the Services may collect or receiveinformation  about you and/or your use of the  Services, including through  the use ofcookies, beacons, and similar technologies. These third parties may use your informationto provide you with advertising that is based on your interests and to measure and analyzead performance, on our Services or other websites or platforms, and combine it withinformation collected across different websites, online services, and other devices. Thesethird parties’ use of your information will be based on their own privacy policies.</p>
                            <p><strong>4. Social Media Services.</strong> If you interact with any Aesthetic Record page or account on asocial media platform, we may share your information with that social media service.Social media services will use that information based on their own privacy policies. Ifyou do not want your information shared in this way, do not connect your social mediaservice account with our Services.</p>
                            <p><strong>5. Aggregate or Anonymous Information.</strong> We also may share other information with thirdparties in a manner that does not identify particular users. For instance, we may sharesuch information to help us determine how parts of Services are used, so that we mayimprove our services. We will also may share aggregate information with our partnersand   other   third   parties   about   how   our   users   collective   demographics   or   how   theycollectively use our Services. We also may share aggregate information with our partnersabout how many advertising impressions were delivered.6.Assignment. In the event of a corporate change in control (for instance, a sale or merger),Aesthetic Record may transfer your personal information to the new party in control orthe party acquiring assets. In such circumstances, we would seek to ensure the acquiringparty   follows   the   practices   described   in   this   Privacy   Policy.  We   cannot   promise,however, that an acquiring company or the merged company will have the same privacypractices or treat your information the same as described in this Privacy Policy.</p>
                            <p><strong>7. Law Enforcement, Legal Process, and Emergency Situations.</strong> In some cases, we mayuse or disclose your personal information to a third party if we are required to do so bylaw or if we in good faith believe that such action is necessary to comply with the law orlegal  process;  to protect,  enforce,  and  defend  against  activities  that  may  threaten  thes ecurity, integrity or availability of our or another party’s products, systems and Services;or to protect, enforce, or defend the legal rights, privacy, safety, or property of Aesthetic Record, its agents, officers, directors, and employees.</p>
                            <p><strong>8. Professional Advisors.</strong>  Aesthetic   Record   may   disclose   your   personal   information   to professional advisors, such as lawyers, bankers, auditors, and insurers, where necessaryin the course of the professional services that they render to us.</p>
                            <p><strong>9. With Your Consent or At Your Direction.</strong> In addition to the sharing described in this Privacy Policy, we may share your information with third parties whenever you consentto or direct such sharing.</p>
                            <p>The Services may link to third-party websites and services that are outside our control. We arenot responsible for the security or privacy of any information collected by these third parties,which operate pursuant to their respective privacy policies.</p>
                        </div>
                        <div className="block">
                            <span className="title">E. Online Tracking Tools</span>
                            <p>Aesthetic Record and our third party partners may use cookies, web beacons, SDKs, and othersimilar technologies to track your use of our Services.</p>
                            <p><strong>1. Cookies.</strong>  Cookies are small text files that are stored in your device’s browser when you visit a website. Cookies make it possible to recognize you as the same user across one ormore browsing sessions, and across one or more websites.  Aesthetic Record and our third party partners use cookies for a variety of purposes, including remembering your sign-in credentials and preferences so that you do not have to input them each time youuse   the   Services;   customizing your experience using the Services, including by determining the most relevant content and advertisements to show you; and allowing usand third parties to monitor site traffic and performance so that we may improve our Services.</p>
                            <p>For more information about cookies, including how to see what cookies have been set on your device and how to manage and delete them, visit www.allaboutcookies.org.</p>
                            <p><strong>2. Web Beacons.</strong> Web beacons (also called “web tags” or “pixels”) are tiny graphics or [scripts   that   communicate   information   from   your   device   to   a   server.  Beacons   can   be embedded in online or mobile content, videos, advertisements, or emails. They allow aserver to read certain types of information from your device, such as when you viewed the beacon (and thus the content in which it is embedded) and the IP address of the device on which you viewed the beacon.  We and third parties use beacons for a variety of purposes, including to analyze the use of our Services and (in conjunction with cookies)to provide content and ads that are more relevant to you.</p>
                            <p><strong>3. SDKs.</strong> SDKs are third-party computer code that we may incorporate into our mobileapplications that may be used for a variety of purposes, including to provide us withanalytics regarding the use of our mobile applications, to integrate with social media, addfeatures or functionality to our app, or to facilitate online advertising.</p>
                        </div>
                        <div className="block">
                            <span className="title">F. Your Privacy Controls and Choices</span>
                            <p>There are a number of ways to opt out of having your online activity and device data collectedby third parties, which we have summarized below. Please note that using these controls and choices   to   opt   out   of   tracking   and   targeting   does   not   mean   that   you   will   not   receive advertising while using our Services or on other websites, nor will it prevent the receipt of interest-based advertising from third parties that do not participate in these programs. It will exclude   you,   however,   from   interest-based   advertising   conducted   through   participating networks   and   platforms,   as   provided by   their   policies   and   choice   mechanisms.    Aesthetic Record provides  you with certain controls and choices regarding our use of your personal information, which may include:</p>
                            <p> <strong>1. Correcting and Updating Account Information.</strong>  By logging into your account or usingour   Services,   you   may   be   able   to   change   certain   account   information.  Your   accountsettings may also permit you to opt-out of some types of notification messages. To protectyour privacy and security, we require your username and password in order to verify youridentity before granting account access or making changes.</p>
                            <p><strong>2. Turning Off Cookies.</strong> Most web browsers automatically accept cookies, but also usually allow you to modify your settings  to disable or reject cookies, including cookies  for interest-based advertising. If you delete your cookies or if you set your web browser to decline cookies, however, some features of the Services may not work or may not work as designed. You can usually find these settings in the Options or Preferences menu of your browser; links to instructions provided by several of the most common browsers are below. You can also learn more at www.allaboutcookies.org.</p>
                            <p>- Cookie settings in Google Chrome</p>
                            <p>- Cookie settings in Firefox</p>
                            <p>- Cookie settings in Internet Explorer</p>
                            <p>- Cookie settings in Safari web and iOS.</p>
                            <p><strong>3. Opting Out of Targeted Advertising.</strong> Many  of   the   third   party   advertisers   that   usetracking or targeting tools in connection with our Services either directly, or are membersof programs that, offer you additional choices regarding the collection and use of yourinformation. You can learn more about the options available to limit these participatingthird parties’ collection and use of your information by visiting their websites:</p>
                            <p>- Opt Out of Interest Based Advertising (National Advertising Initiative)</p>
                            <p>- Your Ad Choices (Digital Advertising Alliance)</p>
                            <p>- Your Online Choices (European Interactive Digital Advertising Alliance)</p>
                            <p>- Users of our mobile apps may opt out of receiving targeted advertising in mobileapps   through   participating   members   of   the   Digital   Advertising   Alliance by installing  the AppChoices  mobile app, available  here, and  selecting  the  user’schoices.</p>
                            <p><strong>4. Blocking Advertising ID Use in your Mobile Settings. </strong> Your mobile device settingsmay provide functionality to limit use of the advertising ID associated with your mobiledevice for interest-based advertising purposes. </p>
                            <p><strong>Mobile App Tracking Opt Out Tools.</strong> You can learn about your options to opt-out ofmobile app tracking by certain advertising networks through your device settings.   For more information about how to change these settings for Apple, Android or Windowsdevices, see:</p>
                            <p>- Apple:  http://support.apple.com/kb/HT4228</p>
                            <p>- Android:  http://www.google.com/policies/technologies/ads/</p>
                            <p>- Windows:  http://choice.microsoft.com/en-US/opt-out</p>
                            <p><strong>6. Social Media Settings.</strong> If you interact with any Aesthetic Record page or account on asocial media platform, you may have the ability to limit the information that we mayobtain   from   the   social   media   platform   by   controlling   your   settings   for   the   particularplatform. For example, you may access and change your settings through the Facebooksettings   page   for  Apps   and   Websites.   If   you   withdraw   our   ability   to   access   certain information from a social media platform, that choice will not apply to information thatwe have already received from that platform.</p>
                            <p><strong>7. Using Privacy Plug-ins or Browsers.</strong> You can block our websites from setting cookiesused   for   interest-based   ads   by   using   a   browser   with   privacy   features,   like  Brave,   orinstalling   browser   plugins   like  Privacy   Badger,  Ghostery  or  uBlock   Origin,   andconfiguring them to block third party cookies/trackers.</p>
                            <p><strong>8. Do Not Track.</strong>  Do Not Track is a privacy preference that users can set in their webbrowsers. When a user turns on the Do Not Track signal, the browser sends a message towebsites requesting them not to track the user. We currently do not respond to “Do NotTrack”   or   similar   signals.       For   information   about   Do   Not   Track,   visit www.allaboutdnt.org</p>
                        </div>
                        <div className="block">
                            <span className="title">G. Third Party Sites, Services, and Applications</span>
                            <p>The   Services   provided   by  Aesthetic   Record   may   contain   links   to   other   websites,   mobileapplications, and other online services operated by third parties, and other websites, mobileapplications, and online services operated by third parties may contain links to our Services. These links are not an endorsement of, or representation that we are affiliated with, any thirdparty.  In addition, our content may be included on web pages or in mobile applications oronline services that are not associated with us.  We do not control third party websites, mobileapplications or online services, and we are not responsible for their actions of their privacy policies. Other websites, mobile applications and Services follow different rules regarding thecollection,   use   and   sharing   of   your   personal   information. We   encourage   you   to   read   the privacy policies of the other websites, mobile applications and online services you use. </p>
                            <p>We rely on third parties to provide many features of our Services using data about your use ofour Services and of other websites.  These third parties may use cookies, web beacons, orother technologies to collect and process your personal data for the purposes of informationstorage and access; personalization of our Services; measurement of and analytics regardingthe use of our Services; content selection, delivery, and reporting; and advertising selection,targeting, delivery, and reporting.</p>
                            <p>For   instance,   third   party   analytics   services   use   cookies,   web   beacons,   and   other   trackingtechnologies to collect information such as your IP address, time of visit, whether you are areturn visitor, and any referring website, in order to help us analyze how users interact withand use the Services, compile reports on the Services’ activity, and provide other data andinsights related to the Services’ usage.</p>
                            <p>We   also   allow   our   third   party   partners,   third   party   ad   serving   networks,   and   unaffiliatedadvertisers to use cookies, web beacons, SDKs, and other tracking technologies to provide adsabout goods and services that may be of interest to you.   Advertisers may place a separatecookie   on   your   computer,   mobile   device,   or   browser,   or   utilize   other   data   collection   andtracking technologies, to collect information such as your IP address, browser type, serverbeing used, area code and zip code associated with your server, and whether you respond toparticular   ads.  Advertisers   may   collect   information   about   your  online   activities   over   time,across  different  computers, devices, and browsers, and across  different websites  and otheronline services. Advertisers may use this information to provide interest-based advertising orother targeted content. </p>
                            <p>Advertisers may use persistent identifiers, however, to track your internet usage across otherwebsites   in   their   networks   beyond   our   Services.  Though   we   restrict   any   attempts   to   re-identify   this   information,   advertisers   may   nonetheless   be   able   to   do   so   by   combininginformation they collect about you when you use the Services with information about youobtained from other sources.</p>
                            <p>In general, the information collected and generated by third parties is processed and stored bythe third parties  and will be subject to their respective privacy policies (which we do notcontrol and for which we are not responsible). We do not control these third parties’ trackingtechnologies or the information they may collect.</p>
                        </div>
                        <div className="block">
                            <span className="title">H. Important Information for California Residents</span>
                            <p>This Section applies only to California residents. It describes how we collect, use andshare Personal Information of California residents in operating our business, and theirrights with respect to that Personal Information.  For purposes of this section, “Personal Information”   has   the   meaning   given   in   the   California   Consumer   Privacy   Act   of   2018(“CCPA”) but does not include information exempted from the scope of the CCPA.</p>
                            <p>How We Collect, Use, and Share your Personal Information.  We collect the followingstatutory categories (as defined by CCPA) of Personal Information:</p>
                            <p><strong>- Identifiers</strong> (e.g., name, site log-in, email address, mailing address, phone number).</p>
                            <p><strong>- Commercial information</strong> (e.g., subscription records, site engagement).</p>
                            <p>- Biometric information.</p>
                            <p><strong>- Online identifiers</strong> (e.g.,   device   identifier,   IP  address,   unique   browser   ID,   cookies,beacons, pixel tags, account login, other unique identifiers).</p>
                            <p><strong>- Internet or other electronic network activity information</strong> (e.g., browsing and searchhistory, site and advertisement interactions).</p>
                            <p><strong>- Geolocation data.</strong> Professional or employment-related information.</p>
                            <p><strong>- Financial information</strong>  (e.g.,  your   financial   account   numbers   or   payment   cardinformation;  please note that a third party payment processor is responsible for allcollection, processing, and storage of your financial information and we do not havedirect access to or possession of any payment card information.)</p>
                            <p><strong>- Education information</strong> (e.g., information you provide when you apply for a job withus).</p>
                            <p><strong>- Protected classification characteristics</strong> (e.g., age or gender;  please note that we donot intentionally collect this information, but it may be revealed in identity data orother information we collect)  </p>
                            <p><strong>- Inferences drawn from any of the information identified in this Section</strong>  (e.g.,information about your interests, preferences, and favorites).</p>
                            <p>The sources from which we collect information are described in Section B of this PrivacyPolicy;   the   business   and   commercial   purposes   for   which   we   collect   this   information   aredescribed in Section C of this Privacy Policy; and the categories of third parties to whom we“disclose” the information for a business purpose are described in Sections C and F of thisPrivacy Policy.</p>
                            <p><strong>Your California Privacy Rights.</strong> As a California resident, you have the rights listed below.However, these rights are not absolute, and in certain cases we may decline your request aspermitted by law.  </p>
                            <p><strong>- Information.</strong> You can request the following information about how we have collectedand used your Personal Information during the past 12 months: </p>
                            <p>1.  The categories of Personal Information that we have collected.oThe categories of sources from which we collected Personal Information.</p>
                            <p>2.  The   business   or   commercial   purpose   for   collecting   and/or   selling   PersonalInformation.</p>
                            <p>3.  The categories of third parties with whom we share Personal Information.</p>
                            <p>4.  Whether we have disclosed your Personal Information for a business purpose,and if so, the categories of Personal Information received by each category ofthird party recipient.</p>
                            <p><strong>- Access.</strong>  You can request a copy of the Personal Information that we have collectedabout you during the past 12 months.  </p>
                            <p><strong>- Deletion.</strong> You can ask us to delete the Personal Information that we have collectedfrom you.  </p>
                            <p><strong>- Opt-out of sales.</strong>  California residents have the right to instruct us to not sell yourPersonal   Information.  However,  Aesthetic   Record   does   not   currently   sell   PersonalInformation of California residents as those terms are defined by current Californialaw.  In the event we choose to do so in the future, we will update this Privacy Policyto provide an opportunity for California residents to be verified and exercise their opt-out rights under that law.  If you have any questions about our existing information sharing   practices,  please   reach   out   to   us   via   the   information   in   the   “Contact   Us” Section below.  </p>
                            <p><strong>- Opt-in.</strong> If we know that you are younger than 16 years old, we will ask for your permission   (or   if   you   are   younger   than   13   years   old,   your   parent’s   or   guardian’s permission) to sell your Personal Information before we do so.</p>
                            <p><strong>- Nondiscrimination.</strong> You are entitled to exercise the rights described above free from discrimination. This means that we will not penalize you for exercising your rights by taking   actions   such   as   denying   you   services;   increasing   the   price/rate   of   services;decreasing service quality; or suggesting that we may penalize you as described above for exercising your rights.</p>
                            <p>How to Exercise your California Rights. California residents may exercise their rights toinformation, access, and deletion described above as follows: - Email privacy@aestheticrecord.com</p>
                            <p><strong>Identity Verification and Additional Information to Needed to Process a Request.</strong>  We reserve the right to confirm your California residence to process your requests and will needto   confirm   your   identity   to   process   your   requests   to   exercise   your   information,   access   ordeletion   rights.  As   part   of   this   process,   government   identification   may   be   required. California residents can empower an “authorized agent” to submit requests on their behalf.  We   will   require   the   authorized   agent   to   have   a   written   authorization   confirming   thatauthority. We cannot process your request if you do not provide us with sufficient detail toallow us to understand and respond to it.</p>
                        </div>
                        <div className="block">
                            <span className="title">I. Important Information for California Residents</span>
                            <p>Nevada  have   the   right   to   instruct   us   not   to   sell   covered   information.     However, Aesthetic Record does not currently sell covered information of Nevada residents as those terms are defined under current Nevada law. In the event we choose to do so in the future, we will update this Privacy Policy to provide an opportunity for Nevada residents to be verifiedand exercise their opt-out rights under that law. If you have any questions about our existing information sharing practices, please reach out to us via the information in the “Contact Us” Section below</p>
                        </div>

                        <div className="block">
                            <span className="title">J. Information for Non-U.S. Residents.</span>
                            <p> As a multi-national company, Aesthetic Record may transmit to and process your informationin a foreign country where privacy laws may be less stringent than the laws in your country. Nonetheless,   where   possible   we   take   steps   to   treat   personal   information   using   the   sameprivacy principles that apply pursuant to the law of the country in which we first receivedyour information. By submitting your personal information to us you agree to the transfer,storage and processing of your information in a country other than your country of residenceincluding,   but   not   necessarily   limited   to,   the   United   States.     If   you   would   like   moreinformation   concerning   our   attempts   to   apply   the   privacy   principles   applicable   in   onejurisdiction   to   data   when   it   goes   to   another   jurisdiction   you   can   contact   us   at privacy@aestheticrecord.com.</p>
                        </div>
                        <div className="block">
                            <span className="title">K. Children’s Privacy .</span>
                            <p>Aesthetic   Record   has   implemented   reasonable   security   measures,   including   the   use   of physical,   technical,   and   administrative   controls,   to   protect   your   information   from unauthorized   access,   disclosure,   use,   and   modification. From   time-to-time,   we   review   our security procedures to consider appropriate new technologies and methods. </p>
                            <p>Please   be   aware,   though,   that   despite   our   efforts,   no   security   measures   are   perfect   or impenetrable. We cannot ensure, and do not warrant or guarantee, that the information you transmit to Aesthetic Record will remain secure, nor do we guarantee that this informationwill not be accessed, disclosed, altered, destroyed or used in an unauthorized manner.  You are responsible   for   the   security   of   your   information   when   using   unencrypted,   open   access,   or otherwise unsecured networks.</p>
                            <p>If we learn of a security breach, we may attempt to notify you electronically so that you cantake appropriate protective steps.   We may also post a notice on our websites if a securitybreach occurs.  Depending on where you live, you may have a legal right to receive a noticeof a security breach in writing. If you have any questions about the security of your personalinformation, please reach out to us via the information in the “Contact Us” Section below.</p>
                        </div>
                        <div className="block">
                            <span className="title">L. Data Storage .</span>
                            <p>How long Aesthetic Records keep the personal information we collect depends on the type of information,  the  purpose for  which  it  is  used,  how   sensitive  it  is, and  similar  factors.   In general, we will retain your personal information for the length of time reasonably needed to fulfill the purposes outlined in this Privacy Policy (including for as long as need to provide you or our customer with products and services), unless a longer retention period is required or permitted by law. We will also retain and use your information for as long as necessary to resolve   disputes   and/or   enforce   our   rights   and   agreements.    Anonymous   and   aggregated information may be stored indefinitely.</p>
                        </div>
                        <div className="block">
                            <span className="title">M. Contact Us .</span>
                            <p>If you have any questions about this Privacy Policy or our privacy practices, please contact usat privacy@aestheticrecord.com, or send mail to:Aesthetic Record, Attn: Privacy Policy, 40 West Gay Street, Columbus, OH 43215.</p>
                        </div>
                    </div>
                </main>
            </div>
        )
    }
}

export default PrivacyPlans;